name: release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:

  create-release:
    name: Create a new release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features